version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install and build package
          command: yarn install --frozen-lockfile

      - run:
          name: Run tests
          command: yarn test --runInBand --no-cache --coverage

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy-docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy Docs Website
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then 
              curl -X POST -d {} ${NETLIFY_HOOK}
            fi

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy-docs:
          requires:
            - test
